// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensoreAPPMVC.Data;

#nullable disable

namespace SensoreAPPMVC.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251205133005_datatable")]
    partial class datatable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeatmapValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<int>("HeatmapId")
                        .HasColumnType("int");

                    b.Property<int>("HeatmapId1")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HeatmapId");

                    b.HasIndex("HeatmapId1");

                    b.ToTable("HeatmapValues");
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.Heatmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Heatmaps");
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.Patient", b =>
                {
                    b.HasBaseType("SensoreAPPMVC.Models.User");

                    b.Property<bool>("CompletedRegistration")
                        .HasColumnType("bit");

                    b.Property<int>("clinicianId")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Patient");
                });

            modelBuilder.Entity("HeatmapValue", b =>
                {
                    b.HasOne("SensoreAPPMVC.Models.Heatmap", null)
                        .WithMany("Values")
                        .HasForeignKey("HeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SensoreAPPMVC.Models.Heatmap", "Heatmap")
                        .WithMany()
                        .HasForeignKey("HeatmapId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heatmap");
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.Heatmap", b =>
                {
                    b.HasOne("SensoreAPPMVC.Models.Patient", "Patient")
                        .WithMany("Heatmaps")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.Heatmap", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("SensoreAPPMVC.Models.Patient", b =>
                {
                    b.Navigation("Heatmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
